/*
 * CourseRejudgeJob.hpp
 *
 *  Created on: 2018年11月9日
 *      Author: peter
 */

#ifndef SRC_MASTER_REJUDGEJOB_COURSEREJUDGEJOB_HPP_
#define SRC_MASTER_REJUDGEJOB_COURSEREJUDGEJOB_HPP_


#endif /* SRC_MASTER_REJUDGEJOB_COURSEREJUDGEJOB_HPP_ */
