/*
 * ExerciseRejudgeJob.hpp
 *
 *  Created on: 2018年11月20日
 *      Author: peter
 */

#ifndef SRC_MASTER_REJUDGEJOB_EXERCISEREJUDGEJOB_HPP_
#define SRC_MASTER_REJUDGEJOB_EXERCISEREJUDGEJOB_HPP_


#endif /* SRC_MASTER_REJUDGEJOB_EXERCISEREJUDGEJOB_HPP_ */
